
name: CI/CD

on:
  workflow_call:
  push:
  pull_request: 
permissions:
  security-events: write
  packages: read
  actions: read
  contents: read
jobs: 

  Validate:
    name: Validate project
    runs-on: ubuntu-latest
    steps:
      
      - name: Git Clone
        uses: actions/checkout@v4
        
      - name: Validate folders
        run: |
          echo "🔍 Validando archivos en la raíz del proyecto..."
          
          if [ -f "./Dockerfile" ]; then
              echo "Dockerfile encontrado"
          else
              echo "Dockerfile NO encontrado en la raíz"
          fi
          
          if [ -f "./pom.xml" ]; then
              echo "pom.xml encontrado"
          else
              echo "pom.xml NO encontrado en la raíz"
          fi
          
          echo "Todos los archivos requeridos están presentes"
                   
  Docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ vars.GH_PAT }}
      AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY }}
    steps:
      
      - name: Git Clone
        uses: actions/checkout@v4
        
      - name: Docker Auth
        run: |
          echo "Docker login"

      - name: Docker Config
        uses: docker/setup-buildx-action@v3
      
      - name: Build app
        run: |
          mvn -q -DskipTests package
      
      - name: Build Image
        env:
          DOCKER_BUILDKIT: 0
        run: | 
          docker build --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg GH_TOKEN=$GH_TOKEN -t clagosu/ms-catalog-content:latest .
          
  Deploy:
    needs: 
      - Docker-build
    runs-on: ubuntu-latest
    steps:
    
      - name: Deploy app
        run: |
          docker run clagosu/ms-catalog-content:latest || true

  Smoke-test:
    needs: 
      - Deploy
    runs-on: ubuntu-latest
    steps:
    
      - name: Execute test
        run: |
          echo "testing"
  
