name: CI Snyk

on:
  workflow_call:
  push:
permissions:
  security-events: write
  packages: write
  actions: write
  contents: write
jobs:
  
  SAST:
    runs-on: ubuntu-latest
    name: Static Application Security Testing
    steps:   
    
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_PAT }}

      #- name: Auth Snyk
        #run: |
          #snyk auth --auth-type=token
        #env:
          #SNYK_TOKEN: ${{ secrets.SYNK_PAT }}

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SYNK_PAT }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
          

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
